openapi: 3.1.0
x-stoplight:
  id: t3eumkqm9y6gi
info:
  title: v1-integration-hub-api
  version: '1.0'
servers:
  - url: 'http://localhost:8085'
paths:
  '/int/vehicle/vin/decode/{vin}':
    parameters:
      - schema:
          type: string
        name: vin
        in: path
        required: true
        description: vehicle VIN number
    get:
      summary: Get Vehicle Info by VIN
      tags: []
      responses:
        '200':
          description: VIN Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VehicleInfo'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: VIN Not Found
      operationId: vin-decode
      description: Retrieve the information of the vehicle with the VIN
components:
  schemas:
    VehicleInfo:
      description: Info of vehicle
      properties:
        make:
          type: string
          example: toyota
        model:
          type: string
          example: highlander
        modelYear:
          type: number
          example: '2020'
        trimLevel:
          type: string
          example: limited
